### PR TITLE
add get_all_connections method

### PR DESCRIPTION
**Pull request by vanatteveldt**
This method will iterate over all pages yielded by a get_connections call and yield the individual items.

I create the new request as a new get_connection call, which I think is nicer than doing a raw request. 
Line 135 is a bit hacky, but I couldn't think of another easy way to get all arguments except for the access token.

It now yields individual items rather than pages, which I think is more useful for most users, but this can be easily changed. 

See https://github.com/mobolic/facebook-sdk/issues/85

### CODE REVIEW

**Comment by martey** [comment]
Thanks for contributing this.

I'd really like to see more documentation before merging this. The new method should be added to the [API Reference](https://github.com/mobolic/facebook-sdk/blob/master/docs/api.rst).

It's also not clear why you need to delete the `access_token` kwarg. Shouldn't it be the same value as passed into the function's `**args` (which should really be renamed to `**kwargs`)?

This looks much cleaner than the previous raw_request pull requests. When this is ready to be merged, I plan to raise a discussion on the Google Group about having it replace `get_connection` instead of becoming a new method.

**Comment by vanatteveldt** [comment]
Thanks. I'll add the needed documentation and test. 

`request` already adds the access token so I figured it would be redundant, but I agree that it also doesn't do any harm. I kept the name `args` from `get_connection`, I figured internal consistency is better than the naming convention. 

One thing that concerns me about using this method is that there is no easy way to do error handling. If you need to retrieve e.g. 100 pages and you get a network failure on page 99, in this implementation it just errors and the data from the first 99 pages is lost. However, I'm not sure how to deal with this as doing e.g. a fixed number of retries with increasing timeout is something I feel is better left to user code, especially since facebook rate limiting is daily (so waiting 10 minutes won't solve a rate limit problem); and returning something like a dict of `{page: results_or_error}` also feels wrong. Any suggestion?

**Comment by martey** [comment]
> One thing that concerns me about using this method is that there is no easy way to do error handling. If you need to retrieve e.g. 100 pages and you get a network failure on page 99, in this implementation it just errors and the data from the first 99 pages is lost.

I am confused - since the method yields individual posts, why would posts from the first 99 pages be lost?

**Comment by matnel** [comment]
What's the status of this PR currently? I would really really hope to see something like this in the SDK :)

**Comment by martey** [comment]
> What's the status of this PR currently?

It still needs documentation and tests. @vanatteveldt, are you still working on this, or would you like someone else to pitch in?

**Comment by matnel** [comment]
I'll try to make these additions next week :)

**Comment by juhopaak** [comment]
I'm currently writing tests and documentation for this method. Does the app you use for testing purposes have test users etc. which I could test the method against? Thanks!

**Comment by gazoon** [comment]
Really useful method, please add it to the library.

**Comment by martey** [comment]
Closing this pull request in favor of #337.

**Pull request closed without merging**
