### PR TITLE
Add support for appsecret_proof

### PR DESCRIPTION
**Pull request by DmytroLitvinov**
This PR is refactored PR from this [PR](https://github.com/mobolic/facebook-sdk/pull/445)

Closes #409

### CODE REVIEW

**Comment by DmytroLitvinov** [comment]
Hello @martey,

I have provided new PR with refactoring after your review.
This PR is ready to be reviewed and merged if it is okay.

Also, could you please release new version on PyPi or you have blockers for that?
I am ready to fix them.

**Comment by nigelgutzmann** [comment]
Wondering if this is going to be merged soon? On July 22, Facebook is ending support for some of their APIs that don't require the appsecret_proof, so we'd like to see this merged and a new version released soon!

**Comment by DmytroLitvinov** [comment]
Ping @martey

**Comment by martey** [comment]
I am aware of this pull request (since I'm [watching this repository](https://github.com/mobolic/facebook-sdk/watchers), I get notifications for each comment), and do not need to be @'ed.

While I've mentioned the importance of [squashing and rebasing commits](https://github.com/mobolic/facebook-sdk/pull/321#pullrequestreview-5861725) in previous iterations of this pull request, I know it's not mentioned in the contributing guidelines. Doing so would make it easier for me to merge this.

**Comment by DmytroLitvinov** [comment]
Refactor PR but get [Graph API exception](https://github.com/mobolic/facebook-sdk/pull/452/checks) on it. 
Does anybody know how to fix it?

**Comment by martey** [comment]
See #458.

**Pull request closed without merging**
