### PR TITLE
Use consistent string formatting

### PR DESCRIPTION
**Pull request by msufa**
Previously the code had a mix of string concatenation and old style formatting. Now all paths for `request` calls are consistently formatted (where it made sense).

### CODE REVIEW

**Comment by martey** [comment]
More consistent consistency is always better, but would it make more sense to switch everything over to new style formatting (`.format()`)?

**Comment by msufa** [comment]
That was actually my initial idea, but from the code it seemed someone really fancies `%` :)

I'll update the PR to make use of the new style text formatting.

**Comment by msufa** [comment]
PR refactored to use new style formatting. @martey please have another look.

**Comment by martey** [comment]
@msufa, would it be possible for you to also change https://github.com/msufa/facebook-sdk/blob/aa1e620cec609d19b8fbd913889ed74f473be6e6/test/test_facebook.py#L71 and squash everything into one commit? I know these are minor changes, so I have no issues doing them if you are too busy.

**Comment by msufa** [comment]
Tests use new style text formatting as well now. Commits squashed. Please have another look @martey

**Pull request merged**
