### PR TITLE
Add a file parameter of put_object for uploading images

### PR DESCRIPTION
**Pull request by punkyoon**
It was related to #360.

A number of commit messages have been modified.

## Usage

```python
 graph.put_object(
     parent_object='post_id',
     connection_name='comments',
     message='Second!',
     file=open('image.jpg', 'rb'))
```

### CODE REVIEW

**Comment by punkyoon** [comment]
@martey

long time no see. I will try to solve the problem asap.

**Comment by martey** [comment]
If liking and/or commenting are no longer possible, don't worry about testing them.

**Comment by punkyoon** [comment]
Hello, How's it going?

I tested to upload video object on post using this code. however it was not working. because videos must be published to `graph-video.facebook.com` instead of `graph.facebook.com` (ref. developers.facebook.com/docs/graph-api/video-uploads)

So, I think this PR is only valid for uploading images now

**Comment by JoaoPedroZucoloto** [comment]
Hello,

I'm using python, and also using this function to send messages:

graph.put_object(txt_id, "messages", message = 'Message goes here')

How can I send a attachment or a photo?

**Comment by Polar1ty** [comment]
> Hello,
> 
> I'm using python, and also using this function to send messages:
> 
> graph.put_object(txt_id, "messages", message = 'Message goes here')
> 
> How can I send a attachment or a photo?

graph.put_object(txt.id, "messages", message='Message goes here', source='url of the photo', link='any link you want to attach')

But how to attach files from local pc i still dont know

**Pull request closed without merging**
