### PR TITLE
Add offline method for get_app_access_token, fix debug_access_token

### PR DESCRIPTION
**Pull request by kz26**

### CODE REVIEW

**Comment by martey** [comment]
In order to release 1.0.0 as soon as possible, I am moving this to the 2.0.0 milestone. This isn't a reflection of the quality of your pull request, but of the lack of free time I currently have to devote to this project.

**Comment by kz26** [comment]
Fixes bug #276.

**Comment by martey** [comment]
It would help me review this if you could rebase this on the master branch (so it is easier for me to see what changes have been made) and squash all "fix" commits.

Ideally, this pull request would only consist of one commit enabling offline support for `get_app_access_token`. Any additional features or fixes (like those to `debug_access_token`) should be their own pull request.

Please feel free to email me if you have questions about this.

**Comment by kz26** [comment]
Done, please see PRs #278 and #279.

**Pull request closed without merging**
