### PR TITLE
Added support for api version 2.12

### PR DESCRIPTION
**Pull request by hendrikschneider**
Added support for api version 2.12

### CODE REVIEW

**Comment by hendrikschneider** [comment]
I checked #399 and saw that I forgot to update docs/api.rst and docs/changes.rst. You already updated the api.rst and I guess you want to update the second one during a new release, right?

**Comment by martey** [comment]
> I guess you want to update the second one on your own during a new release, right?

No, please update the changelog now. I'm pretty forgetful, so if the changelog was only updated at each release, it would be pretty sparse.

I'd also appreciate it if you could [squash all of the commits in this pull request into one](https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit), but if you can't, just let me know.

**Comment by hendrikschneider** [comment]
Done

**Comment by martey** [comment]
I accidentally closed this while trying to resolve a conflict ( :man_facepalming: ), but your commit will be merged in the next few minutes.

**Pull request closed without merging**
