### PR TITLE
Add version to URL path for access_token

### PR DESCRIPTION
**Pull request by wumf-terra**

### CODE REVIEW

**Comment by martey** [comment]
It helps me review pull requests if you use the description to explain what changes you made and why they are necessary or important (e.g. these methods don't work right without a version, adding a version makes the SDK more consistent, etc.).

**Comment by wumf-terra** [comment]
In graph API version 2.3, the response format of `/oauth/access_token` endpoint on authorization code flow was changed.
See https://developers.facebook.com/docs/apps/changelog/#v2_3_changes 
I need to specify version explicitly.

**Comment by martey** [comment]
My log message in e3a7c11ac1c984612df9edfce57f3b6a39b6a9e0 suggests that the "oauth/access_token" endpoint failed when called with a version, at least in the past.

Could you provide more information about your setup? It would help if you could share what version of the API you are using, as well as examples of code that doesn't work with the current SDK and an example that works when your pull request is applied.

Our automated tests don't fully cover all of the behavior around access tokens, so I want to be cautious about making changes to avoid breakage. The Facebook changelog suggests that there might be a larger issue that is also at work here.

**Comment by wumf-terra** [comment]
``` python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os
import sys
import facebook

VALID_API_VERSIONS = ["2.1", "2.2", "2.3", "2.4", "2.5", "2.6", "2.7"]

def main():
    fb_app_id = os.environ["FACEBOOK_APP_ID"]
    fb_app_secret = os.environ["FACEBOOK_SECRET"]

    callback_url = os.environ["FACEBOOK_CALLBACK_URL"]

    args = sys.argv[1:]
    assert len(args) == 2
    api_version = args[0]
    if api_version not in VALID_API_VERSIONS:
        api_version = None

    verification_code = args[1]

    graph = facebook.GraphAPI(version = api_version)
    result = graph.get_access_token_from_code(code =verification_code,
                                                redirect_uri = callback_url,
                                                app_id = fb_app_id,
                                                app_secret = fb_app_secret)

    print 'API VERSION: {0}'.format(api_version)

    if api_version in ["2.3", "2.4", "2.5", "2.6", "2.7"]:
        assert 'expires_in' in result, "no key 'expires_in' in result"
        expires = result.get('expires_in')
    else:
        assert 'expires' in result, "no key 'expires' in result"
        expires = result.get('expires')

    print 'EXPIRES: {0}'.format(expires)

if __name__ == '__main__':
    main()
```

When API v2.2 is expired in next March, API call without version will default to v2.3.
In API v2.3, this script that doesn't work with the current SDK, but it works as expected if my pull request is applied.
I would like to update my app with explicitly calling API v2.3 and test that, before v2.2 is expired.

**Comment by gustavonecore** [comment]
Where was documented that change from **expires** to **expires_in** in the new v2.3?
@martey

**Comment by martey** [comment]
Changes to the Graph API are documented by Facebook in their changelog - see https://developers.facebook.com/docs/apps/changelog#v2_3.

**Pull request closed without merging**
