### PR TITLE
Current docs don't show how to get an access token

### PR DESCRIPTION
**Pull request by k-funk**
I had to pull this from the unit tests to figure out how to get and use access token cleanly. The current example is not enough, and fumbling through the docs/code first made me think that this was the only way to go about it, which is gross/wrong:

```
    graph = facebook.GraphAPI(
        facebook.GraphAPI().get_app_access_token(
            'your_app_id', 'your_app_secret'
        ),
        version='2.2'
    )
```

Please either merge this or update the docs so that someone can get a working example from just this first example.

### CODE REVIEW

**Comment by martey** [comment]
Since `get_app_access_token` retrieves [an application access token and not a user access token](https://developers.facebook.com/docs/facebook-login/access-tokens), I don't plan on merging this.

While the short example in the API documentation is not intended to be a full tutorial, I think such a tutorial would be useful, so I am leaving this open.

**Comment by k-funk** [comment]
The current docs don't show users how to get up and running, so I think this is better than nothing, even if not ideal. This code block is the only code block on the page that `import facebook`, but it doesn't have an intermediate step, which to me, makes it seem like the docs are missing something. Usually when I see an import in docs, that example will be, for the most part, fully runnable.

If it's really not fine in the interim, can you provide a tutorial skeleton page (branch) for me to work on?

**Comment by martey** [comment]
> The current docs don't show users how to get up and running, so I think this is better than nothing, even if not ideal.

Normally I would agree, but since there is already a decent amount of confusion among people using this application about which type of access token they should be using, I worry that explicitly suggesting that application access tokens are the way to go will only cause more problems.

While the SDK is generally agnostic, it was originally built under the assumption that it was being used with a web application, user access tokens, and Facebook's OAuth dialog. It's difficult to show all of this in a code block.

> If it's really not fine in the interim, can you provide a tutorial skeleton page (branch) for me to work on?

Just create a new `tutorial.rst` file and submit a new pull request when you are ready.

**Comment by k-funk** [comment]
What is the general workflow for getting a user access token? I think that if that's the normal use case, an example should go here, even if it's just a couple lines of comments laying out the process very simply.

I'll try to get around to the tutorial.rst this weekend.

**Comment by k-funk** [comment]
https://github.com/mobolic/facebook-sdk/pull/290

**Pull request closed without merging**
